const color1 = { h: 250, s: 60, l: 90 };
const color2 = { h: 70, s: 40, l: 80 };
const color3 = { h: 200, s: 60, l: 80 };

export const blogs = [
  {
    id: "1",
    title: "A Very Very Long Title",
    tags: ["tag1", "tag two"],
    author: { name: "Alexandra Elena", avatar: "", color: color1 },
    date: "02/03/2023",
    image: "",
    color: color1,
  },
  {
    id: "2",
    title: "Another post",
    tags: ["tag1"],
    author: { name: "Author", avatar: "", color: color2 },
    date: "02/05/2023",
    image: "",
    color: color2,
  },
  {
    id: "3",
    title: "Part 2 of 2",
    tags: ["tag1", "tag two"],
    author: { name: "Alexandra Elena", avatar: "", color: color1 },
    date: "02/03/2023",
    image: "",
    color: color1,
  },
  {
    id: "4",
    title: "I'm graduating!",
    tags: [],
    author: { name: "Random UBC Student", avatar: "", color: color2 },
    date: "02/03/2023",
    image: "",
    color: color2,
  },
  {
    id: "5",
    title: "A Very Very Long Title",
    tags: ["tag1", "tag two"],
    author: { name: "Alexandra Elena", avatar: "", color: color3 },
    date: "02/03/2023",
    image: "",
    color: color3,
  },
  {
    id: "6",
    title: "Another post",
    tags: ["tag1"],
    author: { name: "Author", avatar: "", color: color3 },
    date: "02/05/2023",
    image: "",
    color: color3,
  },
  {
    id: "7",
    title: "Part 2 of 2",
    tags: ["tag1", "tag two"],
    author: { name: "Alexandra Elena", avatar: "", color: color2 },
    date: "02/03/2023",
    image: "",
    color: color2,
  },
  {
    id: "8",
    title: "I'm graduating!",
    tags: [],
    author: { name: "Random UBC Student", avatar: "", color: color3 },
    date: "02/03/2023",
    image: "",
    color: color3,
  },
  {
    id: "9",
    title: "Another post",
    tags: ["tag1"],
    author: { name: "Author", avatar: "", color: color1 },
    date: "02/05/2023",
    image: "",
    color: color1,
  },
  {
    id: "10",
    title: "Part 2 of 2",
    tags: ["tag1", "tag two"],
    author: { name: "Alexandra Elena", avatar: "", color: color1 },
    date: "02/03/2023",
    image: "",
    color: color1,
  },
];
